' PUML is a language for diagrams as code you can use this file as a starting place for "Question 2" of the assignment
' If you want to see what this diagram looks like past this file into https://www.planttext.com
' You can also draw the diagram the old fashioned way 
' To understand what a C4 Container diagram is see https://c4model.com

@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(model_designer, "LEGO Model Designer", "A specialist who designs LEGO models digitally")
Person(manufacturing_specialist , "Manufacturing Specialist", "A specialist who needs a list of Item Identifiers")

Container(model_design_client_tool, "Model Design Tool", "C++", "Desktop Application")
Rel(model_designer, model_design_client_tool, "Creates a LEGO Model")

@enduml